### ISSUE TITLE
Alisa WP feedback in next WP iteration

### ISSUE THREAD

**Issue by GavT** [obscuronet/obscuro-whitepaper#65]
(1)	Does the POBI protocol make sense as written (page 12)
a.	The incentives you create and the roadblocks you put in the consensus process are straightforward and sound rational
b.	Is there a model you used for this? Often it’s helpful to cite existing work explicitly so it’s clear that you’re learning from existing work rather than recreating possibly some known problems. 
(2)	Thoughts about the privacy revelation (page 25, 51)
a.	Nothing specific to comment on
(3)	Governance section (page 43)
a.	This section assumes that decentralized applications need to have decentralized governance which is not true. Might want to state directly that you’re looking at a decentralized model because you’re modeling from Ethereum
b.	You might include a paragraph about why you chose those 3 options (did you make them up? Did someone else list them?)
c.	Really like the Ethereum and bitcoin examples. Might be more explicit about what you’re taking from them. 
d.	Unclear why the section begins talking about immutability. I agree with everything you wrote, but might move that to a different spt in the section
e.	“Obscuro powers” is a jarring phrase. You just mean actions that happen in the protocol? I don’t have an alternative.

**Comment by jamescarlyle** [comment]
Will change powers to controls. Add a note about learning from Bitcoin and Ethereum (even though Tudor reflected it in talking about existing governance models). Will not cite formal research.
